name = input("请输入一个名字:")
age = input("请输入一个年龄:")
height = input("请输入一个身高:")
print(name)
print(age)
print(height)
print(type(name))
print(type(age))
print(type(height))

print("%s的年龄是%s，身高是%s" % (name, age, height))